// <auto-generated />
using System;
using Canvia.Infrastructure.Orm.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Canvia.Infrastructure.Orm.Migrations
{
    [DbContext(typeof(CanviaContext))]
    partial class CanviaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Canvia.Infrastructure.Orm.Models.Cp", b =>
                {
                    b.Property<int>("PKID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PKID")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("date")
                        .HasColumnName("FechaCreacion");

                    b.Property<int?>("IdCustomer")
                        .HasColumnType("int")
                        .HasColumnName("IDCustomer");

                    b.Property<string>("Moneda")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("Moneda");

                    b.Property<string>("NumCp")
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("NumCp");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SubTotal");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Total");

                    b.HasKey("PKID")
                        .HasName("PK__CP__21APPSKLPK976P8P");

                    b.HasIndex("IdCustomer");

                    b.ToTable("Cp");
                });

            modelBuilder.Entity("Canvia.Infrastructure.Orm.Models.Customer", b =>
                {
                    b.Property<int>("PKID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PKID")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo")
                        .IsUnicode(false)
                        .HasColumnType("bit")
                        .HasColumnName("Activo");

                    b.Property<string>("Apellidos")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Apellidos");

                    b.Property<string>("Codigo")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Codigo");

                    b.Property<string>("DocIdentidad")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DocIdentidad");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("Nombres")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Nombres");

                    b.HasKey("PKID")
                        .HasName("PK__CUSTOMER__18ASBMMDIK8C5F9S");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Canvia.Infrastructure.Orm.Models.ItemCp", b =>
                {
                    b.Property<int>("PKID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cantidad")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("int")
                        .HasColumnName("Cantidad");

                    b.Property<int?>("IdCp")
                        .HasColumnType("int")
                        .HasColumnName("IDCp");

                    b.Property<int?>("IdProduct")
                        .HasColumnType("int")
                        .HasColumnName("IDProducto");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SubTotal");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Total");

                    b.HasKey("PKID")
                        .HasName("PK__ITEMCP__21APPSKLPK976P8P");

                    b.HasIndex("IdCp");

                    b.HasIndex("IdProduct");

                    b.ToTable("ItemCp");
                });

            modelBuilder.Entity("Canvia.Infrastructure.Orm.Models.Product", b =>
                {
                    b.Property<int>("PKID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PKID")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("Cantidad");

                    b.Property<string>("Codigo")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Codigo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Descripcion");

                    b.Property<bool>("Estado")
                        .IsUnicode(false)
                        .HasColumnType("bit")
                        .HasColumnName("Estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("date")
                        .HasColumnName("FechaCreacion");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Nombre");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Precio");

                    b.HasKey("PKID")
                        .HasName("PK__PRODUCT__18ASBMMDIK8C5F9S");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Canvia.Infrastructure.Orm.Models.Cp", b =>
                {
                    b.HasOne("Canvia.Infrastructure.Orm.Models.Customer", "IdCustomerNavigation")
                        .WithMany("Cps")
                        .HasForeignKey("IdCustomer")
                        .HasConstraintName("FK__CUSTOMER_CP__88P7C438");

                    b.Navigation("IdCustomerNavigation");
                });

            modelBuilder.Entity("Canvia.Infrastructure.Orm.Models.ItemCp", b =>
                {
                    b.HasOne("Canvia.Infrastructure.Orm.Models.Cp", "IdCpNavigation")
                        .WithMany("ItemCps")
                        .HasForeignKey("IdCp")
                        .HasConstraintName("FK__CP_ITEMCP__88P7C438");

                    b.HasOne("Canvia.Infrastructure.Orm.Models.Product", "IdProductNavigation")
                        .WithMany("ItemCps")
                        .HasForeignKey("IdProduct")
                        .HasConstraintName("FK__PRODUCT_ITEMCP__88P7C438");

                    b.Navigation("IdCpNavigation");

                    b.Navigation("IdProductNavigation");
                });

            modelBuilder.Entity("Canvia.Infrastructure.Orm.Models.Cp", b =>
                {
                    b.Navigation("ItemCps");
                });

            modelBuilder.Entity("Canvia.Infrastructure.Orm.Models.Customer", b =>
                {
                    b.Navigation("Cps");
                });

            modelBuilder.Entity("Canvia.Infrastructure.Orm.Models.Product", b =>
                {
                    b.Navigation("ItemCps");
                });
#pragma warning restore 612, 618
        }
    }
}
